/** @format */

export const ItemDefinitions = {
  11111: {
    label: "Chair",
    description: "A comfortable chair",
    weight: 4.2,
    width: 2,
    height: 2,
    image: "./icons/chair.png",
    useEvent: "fl_inventory:useChair",
    removeOnUse: true,
    maxStack: 1,
  },
  11112: {
    label: "Brass",
    description: "A shiny brass item",
    weight: 0.5,
    width: 1,
    height: 1,
    image: "./icons/brass.png",
    useEvent: "fl_inventory:useBrass",
    removeOnUse: true,
    maxStack: 100,
  },
  11113: {
    label: "Micro SMG",
    description: "A small submachine gun",
    weight: 2.5,
    width: 1,
    height: 1,
    image: "./icons/weapon_microsmg.png",
    useEvent: "fl_inventory:useWeaponMicroSMG",
    removeOnUse: false,
    weaponName: "WEAPON_MICROSMG",
    maxStack: 2,
  },
  11114: {
    label: "SMG Ammo",
    description: "A box of SMG ammunition",
    weight: 0.5,
    width: 1,
    height: 1,
    image: "./icons/smg_ammopack.png",
    useEvent: "",
    removeOnUse: false,
    ammoType: "smg",
    maxStack: 10,
  },
};
